export const UPDATE_LIBRARY = "UPDATE_LIBRARY";
export const LIBRARY_STATUS = "LIBRARY_STATUS";

export const PLAYBACK_INIT = "PLAYBACK_INIT";
export const PLAYBACK_STATE = "PLAYBACK_STATE";
export const PLAYBACK_TRACK = "PLAYBACK_TRACK";
export const NAVIGATE_TO = "NAVIGATE_TO";

export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

export const HIDE_PLAYER = "HIDE_PLAYER";
export const SHOW_PLAYER = "SHOW_PLAYER";

export const FETCH_LIST_BOOKMARK_DATA = "FETCH_LIST_BOOKMARK_DATA";
export const FETCH_LIST_BOOKMARK_SUCCESS = "FETCH_LIST_BOOKMARK_SUCCESS";
export const FETCH_LIST_BOOKMARK_ERROR = "FETCH_LIST_BOOKMARK_ERROR";
export const REFRESH_LIST_BOOKMARK_DATA = "REFRESH_LIST_BOOKMARK_DATA";

export const FETCH_LIST_HISTORY_DATA = "FETCH_LIST_HISTORY_DATA";
export const FETCH_LIST_HISTORY_SUCCESS = "FETCH_LIST_HISTORY_SUCCESS";
export const FETCH_LIST_HISTORY_ERROR = "FETCH_LIST_HISTORY_ERROR";
export const REFRESH_LIST_HISTORY_DATA = "REFRESH_LIST_HISTORY_DATA";

export const FETCH_CATEGORY_DATA = "FETCH_CATEGORY_DATA";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_ERROR = "FETCH_CATEGORY_ERROR";
export const ACTIVE_FILTER_CATEGORY = "ACTIVE_FILTER_CATEGORY";
export const DEACTIVE_FILTER_CATEGORY = "DEACTIVE_FILTER_CATEGORY";

export const FETCH_AUTHOR_DATA = "FETCH_AUTHOR_DATA";
export const FETCH_AUTHOR_SUCCESS = "FETCH_AUTHOR_SUCCESS";
export const FETCH_AUTHOR_ERROR = "FETCH_AUTHOR_ERROR";
export const ACTIVE_FILTER_AUTHOR = "ACTIVE_FILTER_AUTHOR";
export const DEACTIVE_FILTER_AUTHOR = "DEACTIVE_FILTER_AUTHOR";

export const FETCH_SPEAKER_DATA = "FETCH_SPEAKER_DATA";
export const FETCH_SPEAKER_SUCCESS = "FETCH_SPEAKER_SUCCESS";
export const FETCH_SPEAKER_ERROR = "FETCH_SPEAKER_ERROR";
export const ACTIVE_FILTER_SPEAKER = "ACTIVE_FILTER_SPEAKER";
export const DEACTIVE_FILTER_SPEAKER = "DEACTIVE_FILTER_SPEAKER";

export const FETCH_SPONSOR_DATA = "FETCH_SPONSOR_DATA";
export const FETCH_SPONSOR_SUCCESS = "FETCH_SPONSOR_SUCCESS";
export const FETCH_SPONSOR_ERROR = "FETCH_SPONSOR_ERROR";
export const ACTIVE_FILTER_SPONSOR = "ACTIVE_FILTER_SPONSOR";
export const DEACTIVE_FILTER_SPONSOR = "DEACTIVE_FILTER_SPONSOR";

export const FETCH_SEARCH_DATA = "FETCH_SEARCH_DATA";
export const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS";
export const FETCH_SEARCH_ERROR = "FETCH_SEARCH_ERROR";
export const REFRESH_SEARCH_DATA = "REFRESH_SEARCH_DATA";
export const CHANGE_SEARCH_TEXT = "CHANGE_SEARCH_TEXT";

export const FETCH_DETAIL_DATA = "FETCH_DETAIL_DATA";
export const FETCH_DETAIL_SUCCESS = "FETCH_DETAIL_SUCCESS";
export const FETCH_DETAIL_ERROR = "FETCH_DETAIL_ERROR";
export const DOWNLOAD_PROCESS = "DOWNLOAD_PROCESS";
export const DOWNLOAD_SUCCESS = "DOWNLOAD_SUCCESS";

export const FETCH_BOOKMARK_DATA = "FETCH_BOOKMARK_DATA";
export const FETCH_BOOKMARK_SUCCESS = "FETCH_BOOKMARK_SUCCESS";
export const FETCH_BOOKMARK_ERROR = "FETCH_BOOKMARK_ERROR";
export const POST_BOOKMARK = "POST_BOOKMARK";
export const POST_BOOKMARK_SUCCESS = "POST_BOOKMARK_SUCCESS";
export const POST_BOOKMARK_ERROR = "POST_BOOKMARK_ERROR";

export const DELETE_BOOKMARK = "DELETE_BOOKMARK";
export const DELETE_BOOKMARK_SUCCESS = "DELETE_BOOKMARK_SUCCESS";
export const DELETE_BOOKMARK_ERROR = "DELETE_BOOKMARK_ERROR";

export const EDIT_BOOKMARK = "EDIT_BOOKMARK";
export const EDIT_BOOKMARK_SUCCESS = "EDIT_BOOKMARK_SUCCESS";
export const EDIT_BOOKMARK_ERROR = "EDIT_BOOKMARK_ERROR";

export const GET_LIBRARY = "GET_LIBRARY";
export const NETINFO_CHANGE = "NETINFO_CHANGE";

export const START_DOWNLOAD = "START_DOWNLOAD";
export const DOWNLOADING = "DOWNLOADING";
export const STOP_DOWNLOAD = "STOP_DOWNLOAD";
export const END_DONWLOAD = "END_DONWLOAD";

export const UPDATE_CHAPTER_DOWNLOAD = "UPDATE_CHAPTER_DOWNLOAD";
export const DOWNLOAD_DONE = "DOWNLOAD_DONE";
export const DOWNLOAD_ERROR = "DOWNLOAD_ERROR";
export const RETRY_DOWNLOAD = "RETRY_DOWNLOAD";

export const FETCH_LIST_NOTIFICATION_DATA = "FETCH_LIST_NOTIFICATION_DATA";
export const FETCH_LIST_NOTIFICATION_SUCCESS =
  "FETCH_LIST_NOTIFICATION_SUCCESS";
export const FETCH_LIST_NOTIFICATION_ERROR = "FETCH_LIST_NOTIFICATION_ERROR";
export const REFRESH_LIST_NOTIFICATION_DATA = "REFRESH_LIST_NOTIFICATION_DATA";

export const FETCH_CONFIG = "FETCH_CONFIG";
export const FETCH_CONFIG_SUCCESS = "FETCH_CONFIG_SUCCESS";
export const FETCH_CONFIG_ERROR = "FETCH_CONFIG_ERROR";

export const UPDATE_CHAPTER_TIME = "UPDATE_CHAPTER_TIME";
export const UPDATE_DRAWER_STATE = "UPDATE_DRAWER_STATE";
export const UPDATE_BOTTOM_SHEET_STATE = "UPDATE_BOTTOM_SHEET_STATE"
